<div class ="bgblack" style="height: 80px;float: left;">
    <div style="margin: 0px auto; position: relative; width: 650px;">
        <div style="float: left;">
            <a href="/" title="Home" >
                <img src="/img/newlogoblack.png" />
            </a>
        </div>  

        <div style="float: left; position: relative; height: 55px; top: 33px;left: -25px;">
            <ul class="nav">
                <li id="home" class="navitem" style="">
                    <a href="/#!/" class="js-hover active_a">
                        <span class="new-wrapper">
                            <i class="nav-new" style="background-image: url('/img/home.png');"></i>
                        </span> Home
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div> 