<div class ="" style="float: left;width: 100%">
    <div style="margin: 0px auto; position: relative;">
        <div style="float: left;margin-top: 12px;">
            <a href="/" title="Home" >
                <img src="/img/newlogoblack.png" />
            </a>
        </div> 

        <div style="float: right; position: relative; height: 55px; top: 40px;left: -25px;">
            <ul class="nav">
                <li id="home" class="navitem" style="">
                    <a href="/#!/" class="js-hover active_a">
                        <!--<span class="new-wrapper">
                            <i class="nav-new home" style="background-position: 0 6px;"></i>
                        </span>--> 
                        <span class="nav-text" style="">
                            Home
                        </span>
                    </a>
                </li>
                <li class="navitem navseparator">
                    <span>
                        |
                    </span>
                </li>
                <li id="about" class="navitem">
                    <a href="/index/about" class="js-hover active_a">
                        <!--<span class="new-wrapper">
                            <i class="nav-new about" style="background-position: 0 -75px;"></i>
                        </span> -->
                        <span class="nav-text" style="left: -9px;">
                            About
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>