<div class="inview-wrapper border-radius border-style"> 
    <div id="yts-article">
      <h1 id="header">
            Nerdeez Community Guidelines
      </h1>
      <div id="article-container">
        <h2>Respect the Nerdeez Community</h2>
        <p>In this document we refer to Files , Movies, Wall posts as Content</p>
        <p class="separator">We're not asking for the kind of respect reserved for nuns, the elderly, and brain surgeons. We mean don't abuse the site. Every cool new community feature on Nerdeez involves a certain level of trust. We trust you to be responsible, and millions of users respect that trust, so please be one of them.</p>
        <h2 class="heading-spacer">We Review Files/Posts/Movies Flagged As Inappropriate</h2>
        <p class="separator">Okay, this one is more about us than you. When a content gets flagged as inappropriate, we review the content to determine whether it violates our Terms of Use&mdash;flagged content are not automatically taken down by the system. If we remove your content after reviewing it, you can assume that we removed it purposefully, and you should take our warning notification seriously. Take a deep breath, read our <a href="/index/terms">Terms of Use</a> and try to see it from our perspective. If you find other Content on Nerdeez with the same violations, please flag them so we can review them as well!</p>
        <h2 class="heading-spacer">Don't Cross the Line</h2>
        <p class="separator">Here are some common-sense rules that will help you steer clear of trouble:</p>
        <ul class="disc">
          <li>Nerdeez is not for pornography or sexually explicit content. If this describes your content, even if it's a video/picture of yourself, don't post it on Nerdeez. Also, be advised that we work closely with law enforcement and we report child exploitation. Please read our <a href="/index/safety/">Safety Tips</a> and stay safe on Nerdeez.</li>
          <li>Don't post content showing bad stuff like animal abuse or drug abuse.</li>
          <li>Graphic or gratuitous violence is not allowed. If your content shows someone getting hurt, attacked, or humiliated, don't post it.</li>
          <li>Nerdeez is not a shock site. Don't post gross-out content of accidents, dead bodies and similar things.</li>
          <li>Respect copyright. Only upload content that you made or that you are authorized to use. This means don't upload content you didn't make, or use information in your contant that someone else owns the copyright to, such as music tracks, snippets of copyrighted programs, Lectures notes, H.W files or videos made by other users, without necessary authorizations. Read our Copyright Tips for more information.</li>
          <li>We encourage free speech and defend everyone's right to express unpopular points of view. But we don't permit hate speech (speech which attacks or demeans a group based on race or ethnic origin, religion, disability, gender, age, veteran status, and sexual orientation/gender identity).</li>
          <li>There is zero tolerance for predatory behavior, stalking, threats, harassment, invading privacy, or the revealing of other members' personal information. Anyone caught doing these things may be permanently banned from Nerdeez.</li>
          <li>Everyone hates spam. Do not create misleading descriptions, tags, titles or thumbnails in order to increase downloads/views. It's not okay to post large amounts of untargeted, unwanted or repetitive content, including comments and private messages.</li>
        </ul>
        <p>Please take these rules seriously and take them to heart. Don't try to look for loopholes or try to lawyer your way around them&mdash;just understand them and try to respect the spirit in which they were created. Violations of the Terms of Use may result in a warning notification or termination of your account. <strong>If your account is terminated you are prohibited from creating any new accounts.</strong></p>
        <h2 class="heading-spacer">Nerdeez is for the Community</h2>
        <p class="separator">Remember that this is your community! Each and every user of Nerdeez makes the site what it is, so don't be afraid to dig in and get involved!</p>
        <ul class="disc">
          <li><strong>Have fun with the site.</strong> There's a lot here to see, and lots of folks making amazing stuff&mdash;one of them might be you! Equipment's getting cheaper and easier to use all the time, so dive in and enjoy.</li>
          <li><strong>Let folks know what you think.</strong> Feedback's part of the experience, and when done with respect, can be a great way to make friends, share stories, and make your time on Nerdeez richer. So leave comments, rate videos/files/posts, make your own responses to content that affect you, enter contests of interest&mdash;there's a lot going on and a lot of ways to participate here.</li>
          <li><strong>You may not like everything you see.</strong> Some of the content here may offend you&mdash;if you find that it violates our Terms of Use, then click "Flag as Inappropriate" under the content you're watching to submit it for review by Nerdeez staff. If it doesn't, then consider just clicking on something else&mdash;why waste time watching content you don't like?</li>
        </ul>
        <p>That's it! Thanks for reading!</p>
        <p>&mdash;The Nerdeez Team</p>
      </div>
    </div>
</div>