<div class="inview-wrapper border-radius border-style">
    <div id="yts-article">
      <h1>A Word on Safety</h1>

      <p>The first thing everyone needs to know is that Nerdeez is NOT for people under the age of 13.</p>

      <h2>Some Things Are Better Left Private...</h2>

      <p>Posting content of yourself, your friends, or your family can be fun and exciting. You never know who will find it&mdash;it might even get featured on the front page, or wind up on the top of the Most Viewed! If your content is personal, Don't post it.</p>

      <h2>Protect Your Secret Identity!</h2>

      <p>If you do post content it is public, make sure there isn't anything in them that could help a stranger figure out who you are or where you live. Personal information like your telephone number or home address should NEVER be shared with other users. Watch out for things like license plate numbers on cars or images of the outside of your home which might accidentally appear in the background of a video and help a stranger to track you down.</p>

      <p>Remember, Nerdeez employees will never ask you for your password, email address, or other account information. Don't be fooled if someone contacts you pretending to be from Nerdeez!</p>

      <h2>Keep Your Cool, Keep Nerdeez Safe</h2>


      <p>Nerdeez doesn't allow content with nudity, graphic violence or hate. If you come across content like this, click the link on the content to flag it as Inappropriate and submit the dialog to report it to Nerdeez.</p>

      <p>Nerdeez has literally MILLIONS of viewers every day and just like in the real world, most of the people are good, but some aren't. So please take care to protect yourself by not posting personal content, keep your identity a secret, your comments clean, and by using the flagging system to report abuse.</p>

      <p>&mdash;The Nerdeez Team</p>
    </div>
</div>