<?php
/**
 * display course page , files , wall etc
 * @param ZEND_DBTABLE_ROW $this -> rCourse the course row 
 * @param ZEND_DBTABLE_ROWSET $this -> rsFiles the files we found 
 * @param String $this -> sError display the error message
 * 
 */
?>


<div class="inview-wrapper">
    
    <?php
    //create the status divs
    ?>
    <div id="error" class="about_status"><?php echo $this -> sError; ?></div>
    <div id="status" class="about_status"><?php echo $this -> sStatus; ?></div>
    
    <?php 
        //create the title for this page
    ?>
    <h1 style="text-align: center;">
        <span class="pink_header span_header">
                <?php echo str_replace('\\', '', $this -> rCourse['title']); ?>
        </span>
        <img src="/img/arrow.gif" />
        <span class="black_header span_header">
            <?php echo str_replace('\\', '', $this -> rCourse['description']); ?>
        </span>    
    </h1>
    
    <div style="margin-top: 20px;">
    <?php 
    //create the file browser
    echo $this -> partial ('partials/fileBrowser.phtml' , array(
        'rsFolders'         => $this -> rsFolders ,
        'rFolder'           => $this -> rFolder ,
        'rsFiles'           => $this -> rsFiles ,
        'rCourse'           => $this -> rCourse ,
    ));
    ?>
    </div>
    
</div>
