<?php
/**
 * the admin controller should pass to this view the following params
 * @param String $this -> sError will display the error messages
 * @param String $this -> sStatus will display the status messages
 * @param String $this -> sTitle will display the title of this admin page
 * @param String $this -> aCols the table columns
 * @param Zend_Db_Table_Rowset $this -> rsRows the rows from the table
 * @param String $this -> sModelName the model name of this db table
 * @param Zend_Db_Table_Rowset $this -> rsPapas all the rows from the parent table
 * @param String $this -> sPapaCol the name of the column which is parent
 */
?>

<?php
//init global vars
$bIsDownload = FALSE;
?>

    
        <!-- will hold all the file upload inputs -->
        <input type="file" multiple="multiple" name="files[]" id="admininsertfilesupload_input" class="adminupload_input"/>
        <!-- end file input list -->
        
        <?php 
        //create the status divs
        ?>
        <div id="error" class="about_status"><?php echo $this -> sError; ?></div>
        <div id="status" class="about_status"><?php echo $this -> sStatus; ?></div>
        
        <?php
        //display the title of this admin page
        ?>
        <h1>
            <?php echo $this -> sTitle; ?>
        </h1>
        
        <?php
        //display the info table
        ?>
        <div style="" class="admin_container">
            <h2>Database table</h2>
            <table style="width: 100%;">

                <?php
                //display the table header
                ?>
                <tr>
                    <td class="admin_table_header">
                        
                    </td>
                    <?php
                    foreach ($this ->aCols as $sCol) {
                    ?>
                    <?php
                    if ($sCol === 'path'){
                        $bIsDownload = TRUE;
                    }
                    if ($sCol === 'id'){
                    ?>
                    <td class="admin_table_header">
                    <?php
                    }
                    else{
                    ?>
                    <td class="admin_table_header admin_table_header_cols">
                    <?php
                    }
                    ?>
                        <?php echo $sCol; ?>
                    </td>
                    <?php
                    }
                    ?>
                    <td class="admin_table_header admin_table_header_control">
                        Update
                    </td>
                    <td class="admin_table_header admin_table_header_control">
                        Delete
                    </td>
                    <?php
                    if ($bIsDownload){
                    ?>
                    <td class="admin_table_header admin_table_header_control">
                        Download
                    </td>    
                    <?php
                    }
                    ?>
                </tr>

                <?php
                //print the table rows
                ?>
                <?php
                //foreach ($this -> rsRows as $rRow){
                if (count($this->paginator)){
                    foreach ($this->paginator as $rRow){
                ?>
                <tr id="row_<?php echo $rRow['id']; ?>">
                    <td class="admin_table_cell">
                        <input class="ksFileBrowserCheckbox" type="checkbox" val="<?php echo $rRow['id']; ?>" />
                    </td>
                    <?php
                    foreach($this -> aCols as $sCol){
                    ?>
                    <td class="admin_table_cell">
                        <?php
                        if ($sCol === 'id'){
                            echo $rRow[$sCol];
                        }
                        elseif (in_array ($sCol, $this -> sPapaCol)) {
                        ?>
                        <select name="<?php echo $sCol; ?>" class="admin_parentcombo <?php echo $sCol; ?>">
                            <?php
                                foreach ($this -> rsPapas[$sCol] as $rPapa) {
                                    if ($rPapa['id'] == $rRow[$sCol]){
                            ?>
                                        <option value="<?php echo $rPapa['id']; ?>" selected="selected">
                                            <?php echo $rPapa['title']; ?>
                                        </option>
                            <?php
                                    }
                                    else{
                            ?>  
                                        <option value="<?php echo $rPapa['id']; ?>">
                                            <?php echo $rPapa['title']; ?>
                                        </option>
                            <?php
                                    }
                            ?>
                                
                            <?php
                                }
                            ?>
                        </select>
                        <?php
                        }
                        else{
                        ?>
                        <p class="<?php echo $sCol; ?>" contenteditable="true">
                            <?php echo $rRow[$sCol]; ?>
                        </p>
                        <?php } ?>
                    </td>
                    <?php
                    }
                    ?>
                    <td class="admin_table_cell">
                        <a href="javascript:void(0)" onclick="ksUpdateRow(<?php echo $rRow['id']; ?> , '<?php echo $this -> sModelName ?>')">
                            <img src="/img/32_save.png" />
                        </a>
                    </td>
                    <td class="admin_table_cell">
                        
                        <a href="javascript:void(0)" onclick="ksDeleteRow(<?php echo $rRow['id']; ?> , '<?php echo $this -> sModelName ?>')">
                            <img src="/img/deletebutton.png" />
                        </a>
                    </td>
                    <?php
                    if ($bIsDownload){
                    ?>
                    <td class="admin_table_header admin_table_header_control">
                        <a href="javascript:void(0)" onclick="ksDownloadRow(<?php echo $rRow['id']; ?> , '<?php echo $this -> sModelName ?>')">
                            <img src="/img/download32.png" />
                        </a>
                    </td>    
                    <?php
                    }
                    ?>
                </tr>
                <?php
                    }
                }
                ?>
            </table>
            <img src="/img/arrow_ltr.png" />
            <a href="javascript:void(0)" onclick="$('.ksFileBrowserCheckbox').attr('checked', true);">
                Check All
            </a>
            /
            <a href="javascript:void(0)" onclick="$('.ksFileBrowserCheckbox').attr('checked', false);">
                UnCheck All
            </a>
            <br/>
            <br/>
            <a href="javascript:void(0)" onclick="ksDeleteSelectedRows('<?php echo $this -> sModelName ?>');">
                Delete selected Courses
            </a>
            <?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'partials/Nerdeez_Pagination_Control.phtml'); ?>
        </div>
        
        <?php 
        //display the insert form
        $serial = rand(0, 99999);
        ?>
        <div style="" class="admin_container">
            <h2>Insert new row</h2>
            <div style="width: 500px; margin: 0 auto;">
                <form method="post" action="/admin/insertrow/">
                    <table style="width: 100%;">
                        <?php 
                        foreach($this -> aCols as $sCol){
                            if($sCol === 'id' || $sCol === 'size' || $sCol === 'md5_hash')continue;
                        ?>    
                        <tr>
                            <td style="padding: 10px; text-align: right; font-weight: bold; font-size: 15px;">
                                <?php echo $sCol; ?>
                            </td>
                            <td style="width: 100%; padding: 10px;">
                                <?php
                                if(in_array($sCol, $this -> sPapaCol)){
                                ?>
                                    <select name="<?php echo $sCol; ?>" class="admin_parentcombo">
                                <?php
                                    foreach ($this -> rsPapas[$sCol] as $rPapa) {
                                ?>
                                        <option value="<?php echo $rPapa['id']; ?>">
                                            <?php echo $rPapa['title']; ?>
                                        </option>
                                <?php
                                    }
                                ?>
                                    </select>
                                <?php
                                }
                                elseif ($sCol === 'path'){
                                ?>
                                    <div id="admininsertfilesupload" class="adminupload" onclick="$('#admininsertfilesupload_input').click();">
                                        <span>upload</span>
                                    </div>
                                    <div id="admininsertfilesupload_files">
                                        <table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery">
                                                <tr class="filesheader">
                                                    <td class="filebrowser-td">Filename</td>
                                                    <td class="filebrowser-td filebrowser-td-left">Size</td>
                                                    <td class="filebrowser-td filebrowser-td-left">Progress</td>
                                                    <td class="filebrowser-td filebrowser-td-left">Delete</td>
                                                </tr>
                                        </tbody></table> 
                                    </div>
                                    <script type="text/javascript">
                                        ksInitUpload('admininsertfilesupload' , 
                                            <?php echo $serial; ?> , 
                                                1 , 
                                                209715200, 
                                                '/(\\.|\\/)(gif|jpe?g|png|bmp|zip|rar|pdf|docx|doc|xls|xlsx|ppt|pptx)$/i' , 
                                                '/admin/upload/');
                                    </script>
                                <?php
                                }
                                else{
                                ?>
                                    <input style="width: 100%;" type="text" name="<?php echo $sCol; ?>" />
                                <?php      
                                }
                                ?>
                            </td>
                        </tr>
                        <?php
                        } 
                        ?>
                        <tr>
                            <td colspan="2" style="text-align: center">
                                <button 
                                    class="submit btn primary-btn js-submit" 
                                    type="submit" 
                                    tabindex="0">Insert
                                </button>
                            </td>
                        </tr>
                    </table>
                    <input type="hidden" name="model" value="<?php echo $this -> sModelName; ?>" />
                    <input type="hidden" name="serial" value="<?php echo $serial; ?>" />
                </form>
            </div>
        </div>
        
        <!-- display the rest of the content file -->
        <?php 
            echo $this->layout()->content;
        ?>
        <!-- end of file content -->
        
