<?php
/**
 * the base layout - general html elements that are identical in all pages
 * all the pages layout will extend this
 */
?> 

<!DOCTYPE html>
<html lang="en">  
    <head> 
        <?php  
            $this->headTitle()->prepend('Nerdeez');
            echo $this->headTitle(); 
        ?> 
        <?php 
            echo $this->headMeta(); 
        ?> 
        <?php 
            $this->headLink()->prependStylesheet('/styles/styles.css');
            $this->headLink(array('rel' => 'SHORTCUT ICON',
                                  'href' => '/img/favicon.ico'),
                                  'PREPEND');
            echo $this->headLink(); 
        ?> 
        <?php        
            echo $this->headStyle(); 
        ?> 
        <?php 
            //attach common javascriopt files
            //$this->headScript()->prependFile('/js/tooltip.js');
            $this->headScript()->prependFile('/js/jquery.ksfunctions.js');
            $this->headScript()->prependFile('/js/jquery.validate.min.js');
            $this->headScript()->prependFile('/js/jquery-1.7.1.min.js');
            echo $this->headScript(); 
        ?> 
      
        
        <script type="text/javascript">
          /*var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-30424827-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();*/

        </script>
    </head> 
    <body>
        <!-- <img src="/img/newlogoblack.png" style="display: none;" /> -->
        <div class="content">
        
        <div class="bgblack" style="height: 80px; position: absolute;width: 100%;"></div>
        
         
        <div id="overlay"></div>
        
        <!--
        main content 
        -->
        
        <?php /* NESTED LAYOUT SUPPORT */ ?> 
        <?php 
            if($this->layout()->nestedLayout){
                $this->layout()->setLayout($this->layout()->nestedLayout);
            } 
            else{
                $this->layout()->setLayout('guest');
            }
            echo $this->layout()->render();

        ?> 
        
        </div>
        
        <div id="glassloading" class="glass">
            
        </div>
        <div class="glass_loaddialog border-radius border-style">
            <h2>Loading ...</h2>
            <div align="center">
                <img src="/img/loading_1.gif" width="100" height="100"/>
            </div>
        </div>
        <div id="success">
            <img src="/img/success.png" />
            <span style="font-size: 100px; position: relative; top: -100px; left: 20px; color: green;">Success</span>
        </div>
        
        <div class="bgblack" style="height: 50px; margin-top: -50px;">
            <div style="color: white; text-align: center;top:5px;position:relative;">
                <div style="">
                    © 2012 Nerdeez<br/>
                    <a href="/index/terms" class="footer_anchor">
                        Terms
                    </a>
                    |
                    <a href="/index/privacy" class="footer_anchor">
                        Privacy
                    </a>
                    |
                    <a href="http://ykapps.com" class="footer_anchor">
                        Created by YKApps
                    </a>
                </div>
            </div> 
        </div>
        
        <!-- Begin error dialog -->
        <div id="nerdeez_error_dialog">
            <div class="nerdeez_error_dialog_header">
                <h2>
                    
                </h2>
            </div>
            <div class="nerdeez_error_dialog_body kscenter">
                <div class="kscenter-img"> 
                    <img width="142" height="105" src="/img/searchface.png">    
                </div>
                <div class="kscenter-text">
                    
                </div>
            </div>
            <div style="text-align: center; width: 100%; position: static; margin-top: 20px;">
                <button 
                    style="top: -1px; height: 36px;" 
                    class="submit btn primary-btn js-submit" 
                    type="button" 
                    onclick="$('#nerdeez_error_dialog').fadeOut('normal');$('.glass').slideToggle('normal');">
                    <span class="button-text">
                    OK
                    </span>
                </button>
            </div>
        </div>
        <!-- End error dialog-->
        
    </body> 
</html>