<?php
/**
 * the base layout - general html elements that are identical in all pages
 * all the pages layout will extend this
 * @param String $this -> sUrl holds the site url for the facebook plugin
 */
?> 

<!DOCTYPE html>
<html lang="en">  
    <head> 
        <?php  
            $this->headTitle()->prepend('Nerdeez');
            echo $this->headTitle(); 
        ?> 
        <?php 
            echo $this->headMeta(); 
        ?> 
        <meta property="og:image" content="http://www.nerdeez.com/img/90X90.png"/> 
        <?php 
            $this->headLink(array('rel' => 'SHORTCUT ICON',
                                  'href' => '/img/favicon.ico'), 
                                  'PREPEND');
            echo $this->headLink(); 
        ?> 
        <?php        
            echo $this->headStyle(); 
        ?> 
        <?php 
            //attach common javascriopt files
            echo $this->headScript(); 
        ?> 
      
         <script src="//connect.facebook.net/en_US/all.js"></script>
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-36919461-1']);
            _gaq.push(['_trackPageview']);

            (function() {
              var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
              ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>
    </head> 
    <body>
        <!-- Begin facebook stuff -->
        <div id="fb-root"></div>
        <script>
          // Additional JS functions here
          window.fbAsyncInit = function() {
            FB.init({
              appId      : '410909982317797', // App ID
              channelUrl : '//www.nerdeez.com/channel.html', // Channel File
              status     : true, // check login status
              cookie     : true, // enable cookies to allow the server to access the session
              xfbml      : true  // parse XFBML
            });

            //init the login button
            button = document.getElementById('fbc-login-button');
            button.onclick = function() {
                FB.getLoginStatus(function(response) {
                    if (response.authResponse) {
                        this.location = 'http://<?php echo $this -> layout() -> sUrl; ?>/login/facebook/token/' +  response.authResponse.accessToken;
                    }
                    else {
                        FB.login(function(response) {
                            if (response.authResponse) {
                                this.location = 'http://<?php echo $this -> layout() -> sUrl; ?>/register/facebook/token/' +  response.authResponse.accessToken;
                            }}, {scope: 'email'});
                    }
               });
            };
            
            //init the registration button
            button = document.getElementById('fbc-register-button');
            button.onclick = function() {
                FB.getLoginStatus(function(response) {
                    if (response.authResponse) {
                        this.location = 'http://<?php echo $this -> layout() -> sUrl; ?>/login/facebook/token/' +  response.authResponse.accessToken;
                    }
                    else {
                        FB.login(function(response) {
                            if (response.authResponse) {
                                this.location = 'http://<?php echo $this -> layout() -> sUrl; ?>/register/facebook/token/' +  response.authResponse.accessToken;
                            }}, {scope: 'email'});
                    }
               });
            };
            
          };

          // Load the SDK Asynchronously
          (function(d){
             var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
             if (d.getElementById(id)) {return;}
             js = d.createElement('script'); js.id = id; js.async = true;
             js.src = "//connect.facebook.net/en_US/all.js";
             ref.parentNode.insertBefore(js, ref);
           }(document));
       
           function login() {
                FB.login(function(response) {
                    if (response.authResponse) {
                        // connected
                         testAPI();
                    } else {
                        // cancelled
                    }
                });
            }
        
            function testAPI() {
                console.log('Welcome!  Fetching your information.... ');
                FB.api('/me', function(response) {
                    console.log('Good to see you, ' + response.name + '.');
                });
            }
       
        </script>
        <!-- End facebook stuff -->
        
        <!-- The template to display files available for upload -->
        <script id="template-upload" type="text/x-tmpl">
        {% for (var i=0, file; file=o.files[i]; i++) { %}
            <tr class="template-upload fade">
                <td class="name"><span>{%=file.name%}</span></td>
                <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
                {% if (file.error) { %}
                    <td class="error" colspan="1">{%=locale.fileupload.errors[file.error] || file.error%}</td>
                {% } else if (o.files.valid && !i) { %}
                    <td style="padding-left: 5px; padding-right: 5px;width:50%;">
                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>
                    </td>

                {% } else { %}
                    <td colspan="2"></td>
                {% } %}
                <td class="cancel">{% if (!i) { %}
                    <button class="btn btn-warning primary-btn">
                        <div class="buttongarbageicon"></div>
                    </button>
                {% } %}</td>
            </tr>
        {% } %}
        </script>
        <!-- The template to display files available for download -->
        <script id="template-download" type="text/x-tmpl">
        {% for (var i=0, file; file=o.files[i]; i++) { %}
            <tr class="template-download fade">
                {% if (file.error) { %}
                    <td class="name"><span>{%=file.name%}</span></td>
                    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
                    <td class="error" colspan="1">{%=locale.fileupload.errors[file.error] || file.error%}</td>
                {% } else { %}

                    <td class="name">
                        {%=file.name%}
                    </td>
                    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
                    <td class="filebrowsercomplete" >COMPLETE</td>
                {% } %}
                <td class="delete">
                    <button class="btn btn-warning primary-btn" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                        <div class="buttongarbageicon"></div>
                    </button>
                </td>
            </tr>
        {% } %}
        </script>
        
        
        <?php /* NESTED LAYOUT SUPPORT */ ?> 
        <?php 
            if($this->layout()->nestedLayout){
                $this->layout()->setLayout($this->layout()->nestedLayout);
            } 
            else{
                $this->layout()->setLayout('guest');
            }
            //echo $this->layout()->render();

        ?> 
        
        <!-- the black on top -->
        <div class="bgblack" style="height: 80px; position: absolute;width: 100%;top:0;"></div>
        <!-- end -->
         
        <!-- begin glass to prevent background clicks -->
        <div id="glassloading" class="glass"></div>
         <!-- end glass to prevent background clicks -->
        
        <!-- begin loading screen -->
        <div class="glass" style="z-index: 100;" id="loadingball">
            <div class="loading" 
                 style="left: 50%;position: relative;top: 50%;">
            </div>
        </div>
        <!-- end loading screen  -->
        
        
        
        
        <!-- will hold all the content -->
        <div id="container" class="wrapper">
            
            <!-- begin of menu-->
            <div id="header">
                <div class ="" style="float: left;width: 100%">
                    <div style="margin: 0px auto; position: relative;">
                        <div style="float: left;margin-top: 12px;">
                            <a href="/" title="Home" >
                                <img src="/img/newlogoblack.png" />
                            </a>
                        </div> 
                        
                        <!-- begin hello user -->
                        <?php
                        if ($this -> layout() -> isRegistered):
                        ?>
                        <div style="color: white; position: relative; float: left; width: 183px; left: 100px; top: 33px;">
                            <h3>
                                Hi, <span class="userdetails_nickname"><?php echo $this -> layout() -> user -> title; ?> </span><a 
                                    href="javascript:void(0)" 
                                    onclick="showChangeNameDialog();" 
                                    onmouseout="tooltip.hide();" 
                                    onmouseover="tooltip.show('Change your Nickname');">
                                    <img src="/img/A_PencilDyn_Sm_N.png"/>
                                </a>
                            </h3>
                        </div>
                        <?php 
                        endif;
                        ?>
                        <!-- end hello user -->

                        <div style="float: right; position: relative; height: 55px; top: 40px;left: -25px;">
                            <ul class="nav">
                                <li id="home" class="navitem" style="">
                                    <a href="/#!/" class="js-hover active_a">
                                        <!--<span class="new-wrapper">
                                            <i class="nav-new home" style="background-position: 0 6px;"></i>
                                        </span>--> 
                                        <span class="nav-text" style="">
                                            Home
                                        </span>
                                    </a>
                                </li>
                                <li class="navitem navseparator">
                                    <span style="position: relative; top: -2px;">
                                        |
                                    </span>
                                </li>
                                <?php 
                                //will display the login and register only if the user is not logged in
                                if (!$this -> layout() -> isRegistered):
                                ?>
                                    <li id="menu_register" class="navitem" style="">
                                        <a href="javascript:void(0)" class="js-hover active_a" onclick="showRegisterMenu();">
                                            <span class="nav-text" style="">
                                                Register
                                            </span>
                                        </a>
                                    </li>
                                    <li class="navitem navseparator">
                                        <span style="position: relative; top: -2px;">
                                            |
                                        </span>
                                    </li>
                                    <li id="menu_login" class="navitem" style="">
                                        <a href="javascript:void(0)" class="js-hover active_a" onclick="showLoginMenu();">
                                            <span class="nav-text" style="">
                                                Login
                                            </span>
                                        </a>
                                    </li>
                                    <li class="navitem navseparator">
                                        <span style="position: relative; top: -2px;">
                                            |
                                        </span>
                                    </li>
                                <?php 
                                //will display the menu for registered users
                                else :
                                ?>
                                    <li id="menu_register" class="navitem" style="">
                                        <a href="/login/logout/" class="js-hover active_a">
                                            <span class="nav-text" style="">
                                                Logout
                                            </span>
                                        </a>
                                    </li>
                                    <li class="navitem navseparator">
                                        <span style="position: relative; top: -2px;">
                                            |
                                        </span>
                                    </li>
                                <?php 
                                endif;
                                ?>
                                <li id="about" class="navitem">
                                    <a href="/index/about" class="js-hover active_a">
                                        <!--<span class="new-wrapper">
                                            <i class="nav-new about" style="background-position: 0 -75px;"></i>
                                        </span> -->
                                        <span class="nav-text" style="left: -9px;">
                                            About
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end of menu -->
            
            <!-- Begin like button -->
            <div class="menu_facebooklike">
                <iframe 
                    src="http://www.facebook.com/plugins/like.php?href=<?php echo $this -> layout() -> sUrl; ?>"
                    scrolling="no" frameborder="0"
                    style="border:none; width:450px; height:80px">
                </iframe>
            </div>
            <!--  End like button -->
            
            <!-- begin hold the main content -->
            <div id="body" class="wrapper"">
                <?php echo $this->layout()->render(); ?>
            </div>
            
        </div>
        <!-- end hold all the content -->
        
        
        <!-- begin change name dialog -->
        <div id="changenamedialog" class="flagdialog dialogbg dialog" style="width: 534px;height: 232px;">
            <div class="bgblack flagdialog_header" >
                <h2 style="color: white; margin: 2px auto 0px; position: relative; top: 10px; font-weight: normal; font-size: 18px; width: 210px;">
                    Change your nickname
                </h2>
                <a href="javascript:void(0)" onclick="$('#changenamedialog').fadeOut('normal');$('#glassloading').fadeOut('fast');" class="closedialog" style="position: relative; top: -42px; left: 23px;">
                    <span>
                    X
                    </span>
                </a>
            </div>
            <div id="change_nickname_dialog_error">
                <table style="width: 100%">
                    <tr>
                        <td>
                            <img src="/img/X.png" width="64" />
                        </td>
                        <td>
                            <p></p>
                        </td>
                    </tr>
                </table>
            </div>
            <div id="change_nickname_dialog_success">
                <table style="width: 100%;">
                    <tr>
                        <td>
                            <img src="/img/Success1.png" width="64" />
                        </td>
                        <td>
                            <p>Successfully changed your nickname</p>
                        </td>
                    </tr>
                </table>
            </div>
            <div id="change_nickname_dialog_body">
                <div class="flagdialog_body">
                    <p style="text-align: center;">
                        Write your new nickname in the text box below (up to 20 letters).
                    </p>
                </div>
                <div style="width: 400px; margin: 0px auto; position: relative; top: -18px;">
                    <table style="width: 100%;">
                        <tr>
                            <td>
                                <div class="front-card">
                                    <div class="placeholding-input searchcourse flex-table-form">
                                        <input 
                                                        type="text" 
                                                        autocomplete="on" 
                                                        title="Email" 
                                                        name="email" 
                                                        class="text-input email-input"
                                                        style="width: 100%; position: relative !important;"
                                                        id="changenickname_textbox"
                                                        maxlength="20" />
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: right">
                                <button class="filebrowserbutton" type="button" onclick="$('#loginregistererrordialog').fadeOut('normal');updateNickname();" value="Submit" style="margin-top: 10px; height: 38px; width: 100px; float: right;">
                                    Submit
                                </button>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>      
        <!-- begin change name dialog -->
        
        <!-- begin footer -->
        <div id="footer" class="bgblack">
            <div>
                <div style="color: white; text-align: center;top:5px;position:relative;">
                    <div style="">
                        © 2012 Nerdeez<br/>
                        <a href="/index/terms" class="footer_anchor">
                            Terms
                        </a>
                        |
                        <a href="/index/privacy" class="footer_anchor">
                            Privacy
                        </a>
                        |
                        <a href="/index/communityguidelines" class="footer_anchor">
                            Community Guidelines
                        </a>
                        |
                        <a href="/index/safety" class="footer_anchor">
                            Safety Tips
                        </a>
                         
                    </div>
                </div> 
            </div>
        </div>
        <!-- end footer -->
        
        <!-- common js initialization here -->
        <script type="text/javascript">
            initCommonActions();
        </script>
        <!-- end common -->
        
    </body> 
</html>
