<?php
/**
 * the base layout - general html elements that are identical in all pages
 * all the pages layout will extend this
 */
?> 

<!DOCTYPE html>
<html lang="en">  
    <head> 
        <?php  
            $this->headTitle()->prepend('Nerdeez');
            echo $this->headTitle(); 
        ?> 
        <?php 
            echo $this->headMeta(); 
        ?> 
        <?php 
            $this->headLink()->prependStylesheet('/styles/styles.css');
            $this->headLink()->prependStylesheet('/styles/superfish-navbar.css');
            $this->headLink()->prependStylesheet('/styles/superfish-vertical.css');
            $this->headLink()->prependStylesheet('/styles/superfish.css');
            $this->headLink(array('rel' => 'SHORTCUT ICON',
                                  'href' => '/img/favicon.ico'),
                                  'PREPEND');
            echo $this->headLink(); 
        ?> 
        <?php        
            echo $this->headStyle(); 
        ?> 
        <?php 
            //attach common javascriopt files
            //$this->headScript()->prependFile('/js/tooltip.js');
            $this->headScript()->prependFile('/js/jquery.ksfunctions.js');
            $this->headScript()->prependFile('/js/jquery.ez-pinned-footer.js');
            $this->headScript()->prependFile('/js/superfish.js');
            $this->headScript()->prependFile('/js/jquery.validate.min.js');
            $this->headScript()->prependFile('/js/jquery-1.7.1.min.js');
            echo $this->headScript(); 
        ?> 
      
        
        <script type="text/javascript">
          /*var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-30424827-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();*/

        </script>
        <script type="text/javascript">
            
        </script>
    </head> 
    <body>
        
        <?php /* NESTED LAYOUT SUPPORT */ ?> 
        <?php 
            if($this->layout()->nestedLayout){
                $this->layout()->setLayout($this->layout()->nestedLayout);
            } 
            else{
                $this->layout()->setLayout('guest');
            }
            //echo $this->layout()->render();

        ?> 
        
        <!-- the black on top -->
        <div class="bgblack" style="height: 80px; position: absolute;width: 100%;top:0;"></div>
        <!-- end -->
         
        <!-- will hold all the content -->
        <div id="container" class="wrapper">
            
            <!-- will hold the header menu and such -->
            <div id="header">
                <?php echo $this->layout() ->menu;  ?>
            </div>
            <!-- end header -->
            
            <!-- begin hold the main content -->
            <div id="body" class="wrapper">
                <?php echo $this->layout()->render(); ?>
            </div>
            
        </div>
        <!-- end hold all the content -->
        
        
        
        <!-- begin glass to prevent background clicks -->
        <div id="glassloading" class="glass"></div>
         <!-- end glass to prevent background clicks -->
        
        <!-- begin loading screen -->
        <div class="glass_loaddialog border-radius border-style">
            <h2>Loading ...</h2>
            <div align="center">
                <img src="/img/loading_1.gif" width="100" height="100"/>
            </div>
        </div>
        <!-- end loading screen  -->
        
        <!-- begin report success failure -->
        <div id="success">
            <img src="/img/success.png" />
            <span style="font-size: 100px; position: relative; top: -100px; left: 20px; color: green;">Success</span>
        </div>
        <!-- end report success failure -->
        
        
        <!-- begin footer -->
        <div id="footer" class="bgblack">
            <div>
                <div style="color: white; text-align: center;top:5px;position:relative;">
                    <div style="">
                        © 2012 Nerdeez<br/>
                        <a href="/index/terms" class="footer_anchor">
                            Terms
                        </a>
                        |
                        <a href="/index/privacy" class="footer_anchor">
                            Privacy
                        </a>
                        |
                        <a href="/index/communityguidelines" class="footer_anchor">
                            Community Guidelines
                        </a>
                        |
                        <a href="/index/safety" class="footer_anchor">
                            Safety Tips
                        </a>
                        |
                        <a href="http://ykapps.com" class="footer_anchor">
                            Created by YKApps
                        </a>
                    </div>
                </div> 
            </div>
        </div>
        <!-- end footer -->
        
        <!-- common js initialization here -->
        <script type="text/javascript">
            initCommonActions();
        </script>
        <!-- end common -->
        
    </body> 
</html>