<?php 
/**
 * second layer of layout will include stuff needed for the index page 
 * and similar  pages in the same format
 */
?> 

    <div class="wrapper"> 
        <div class ="bgblack" style="height: 80px;float: left;">
            <div style="margin: 0px auto; position: relative; width: 650px;">
                <div style="float: left;">
                    <a href="/" title="Home" >
                        <img src="/img/newlogoblack.png" />
                    </a>
                </div> 

                <div style="float: left; position: relative; height: 55px; top: 33px;left: -25px;">
                    <ul class="nav">
                        <li id="home" class="navitem" style="">
                            <a href="/#!/" class="js-hover active_a">
                                <span class="new-wrapper">
                                    <i class="nav-new" style="background-image: url('/img/home.png');"></i>
                                </span> Home
                            </a>
                        </li>
                        <li id="about" class="navitem">
                            <a href="/index/about" class="js-hover active_a">
                                <span class="new-wrapper">
                                    <i class="nav-new" style="background-image: url('/img/about_us20.png');"></i>
                                </span> About
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
    <?php 
        echo $this->layout()->content;
    ?>
</div>
    








