<?php 
/**
 * second layer of layout will include stuff needed for the guest view
 */
?> 

    <!-- start of login/register dialog -->
    <?php
    echo $this -> partial ('partials/loginregister.phtml', array(
        'register_status' => $this -> layout() -> register_status, 
        'login_status' => $this -> layout() -> login_status, 
        'email' => $this -> layout() -> email));
    ?>
    <!-- end of login/register dialog -->
        
    <?php 
        echo $this->layout()->content;
    ?>

    











