<div style="background: none repeat scroll 0px 0px transparent; border: medium none; margin-top: 154.667px;" class="front-searchcourse"> 
    <div id="searchcourseform" style="width: 700px; margin: 0px auto;">
        <table style="margin: 0 auto;">
            <tbody><tr>
                <td style="padding: 5px; vertical-align: top; width: 161px;" rowspan="2">
                    <img height="100" width="138" src="/img/Error.png">
                </td>
                <td style="height: 55px; vertical-align: middle;">
                    <h1 style="color: #E62A59;">
                        <?php echo $this -> title; ?>
                    </h1>
                    <p>
                        <?php echo $this -> message; ?>
                    </p>
                    <p>
                        <?php echo $this -> exception; ?>
                    </p>
                </td>
            </tr>
        </tbody></table>
    </div>
</div>
