<?php
/**
 * login form
 * @param String $this -> sId the id of the forum
 */
?>


<div class="front-card">
    <div class="front-signin js-front-signin" style="height: 130px;">
        <form 
            method="post" 
            id="<?php echo $this -> sId; ?>"
            class="signin" 
            action="https://<?php $ksfunctions = new Application_Model_KSFunctions(); echo $ksfunctions -> sGetUrl(); ?>/login/login">
            <div class="placeholding-input username" style="margin: 0 auto;position: relative;top: 12px;width: 276px;left: 0">
                <input 
                        type="text" 
                        autocomplete="on" 
                        title="Email" 
                        name="email" 
                        class="text-input email-input"
                        maxlength="100" />
                <span class="placeholder">Email</span>
                <div class="register-error-placeholder email"></div>
            </div>          
            <table class="flex-table password-signin" style="margin: 0 auto !important;position: relative !important;top: 28px !important;width: 276px !important;left: 0;">
                <tbody>
                    <tr>
                        <td class="flex-table-primary">
                            <div class="placeholding-input password flex-table-form">
                                <input 
                                    type="password" 
                                    title="Password" 
                                    name="password"
                                    class="text-input flex-table-input"
                                    maxlength="100" />
                                <span class="placeholder">Password</span>
                                <div class="register-error-placeholder password"></div>
                            </div> 
                        </td>
                        <td class="flex-table-secondary">
                            <button 
                                    class="submit btn primary-btn flex-table-btn js-submit" 
                                    type="submit" 
                                    tabindex="0">Login
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
                <div class="remember-forgot" style="left: 12px;margin: 0;position: relative;top: 42px;width: 276px;">
                    <label class="remember">
                        <input type="checkbox" name="rememberme" value="1" checked="on"/>
                        <span>Remember me</span>
                    </label>
                    <span class="separator">·</span>
                    <a href="/login/forgot" class="forgot2">Forgot password?</a>
                </div>
         </form>
    </div>
</div>

<script type="text/javascript">
    loadLogin('<?php echo $this -> sId; ?>');
</script>

