<div id="loginregister" class="loginregister">
    <div style="width: 100%; text-align: right;">
        <a style="position: relative; clear: both; display: inline-block; top: 17px; left: 17px;" class="closedialog" onclick="$('#loginregister').fadeOut('normal');$('#glassloading').fadeOut('fast');" href="javascript:void(0)">
            <span>
            X
            </span>
        </a>
    </div>
    <div class="loginregister_header">
        <a id="logintab" class="loginregister_tab active" onclick="showSignIn();">
            <span class="dialogfont " style="left: 79px;">Sign In</span>
        </a>
        <a id="registertab" class="loginregister_tab" onclick="showRegister();">
            <span class="dialogfont" style="left: 74px;">Register</span>
        </a>
    </div>
    <div class="loginregister_body dialogbg">
        <!-- begin of login -->
        <div style="width: 330px; margin-right: auto; margin-bottom: 0px; margin-left: auto; height: 242px; position: relative; top: 67px;" id="login">
            <form 
            method="post" 
            action="https://<?php $ksfunctions = new Application_Model_KSFunctions(); echo $ksfunctions -> sGetUrl(); ?>/login/login">
            <div style="height: 57px;">
                <table style="width: 100%;">
                    <tr>
                        <td>
                            <span class="dialogfontbody">
                            Email
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="front-card">
                                <div class="searchcourse flex-table-form">
                                     <input 
                                        type="text" 
                                        autocomplete="on" 
                                        title="Email" 
                                        name="email" 
                                        class="text-input email-input nerdeez_dialog"
                                        style="width: 100%"
                                        maxlength="100" />
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="register-error-placeholder email"></div>
                        </td>
                    </tr>
                </table>
            </div>
            <div style="height: 57px; margin-top: 16px;">
                <table style="width: 100%; height: 78px;">
                    <tr style="height: 20px">
                        <td>
                            <span class="dialogfontbody">
                            Password
                            </span>
                        </td>
                    </tr>
                    <tr style="height: 25px;">
                        <td style="vertical-align:top;">
                            <div class="front-card">
                                <div class="searchcourse flex-table-form">
                                    <input 
                                        type="password" 
                                        title="Password" 
                                        name="password"
                                        style="width: 100%;"
                                        class="text-input email-input nerdeez_dialog"
                                        maxlength="100" />
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="register-error-placeholder password"></div>
                        </td>
                    </tr>
                    <tr style="height: 20px;">
                        <td>
                            <a href="/login/forgot" class="forgot2">Forgot your password?</a>
                        </td>
                    </tr>
                </table>
            </div>
            <div style="margin-top: 54px;">
                <div style="float: left; position: relative; top: 12px; width: 116px;">
                    <label class="remember">
                        <input type="checkbox" name="rememberme" value="1" checked="on"/>
                        <span class="dialogfontbody" style="position: relative; top: -2px;">Remember me</span>
                    </label>
                </div>
                <div style="width: 98px; float: right;height: 44px;">
                    <button 
                            class="filebrowserbutton" 
                            type="submit" 
                            style="height: 44px !important;"
                            tabindex="0">SIGN IN
                    </button>
                </div>
            </div>
            </form>
        </div>
        <!-- end of login -->
        
        <!-- begin of register -->
        <div id="register" style="margin-right: auto; margin-bottom: 0px; margin-left: auto; position: relative; top: 27px; width: 330px;">
            <form action="https://<?php $ksfunctions = new Application_Model_KSFunctions(); echo $ksfunctions ->sGetUrl();  ?>/register/signup" class="signin registerform" method="post">
                <div style="height: 57px">
                    <table style="width: 100%;">
                        <tr>
                            <td>
                                <span class="dialogfontbody">
                                Email
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="front-card">
                                    <div class="username" style="width: 100%">
                                        <input 
                                                type="text" 
                                                autocomplete="on" 
                                                title="Email" 
                                                name="email" 
                                                id="register_input_email"
                                                class="text-input email-input nerdeez_dialog"
                                                maxlength="100" 
                                                style="width: 100%;" />
                                        
                                    </div>          
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="register-error-placeholder email"></div>
                            </td>
                        </tr>
                    </table>
                </div>
                <div style="height: 57px;margin-top: 15px;">
                    <table style="width: 100%;">
                        <tr>
                            <td>
                                <span class="dialogfontbody">
                                Password
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="front-card">
                                    <div class="username" style="width: 100%">
                                        <input type="password" maxlength="100" 
                                               class="text-input email-input pass nerdeez_dialog" 
                                               name="password" 
                                               id="register_input_password"
                                               title="Password" 
                                               style="width: 100%;" />
                                    </div>          
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="register-error-placeholder password"></div>
                            </td>
                        </tr>
                    </table>
                </div>
                <div style="height: 57px;margin-top: 15px;">
                    <table style="width: 100%;">
                        <tr>
                            <td>
                                <span class="dialogfontbody">
                                Retype Password
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="front-card">
                                    <div class="username" style="width: 100%">
                                        <input type="password" maxlength="100" 
                                               class="text-input email-input nerdeez_dialog" 
                                               name="repassword" 
                                               title="Password" 
                                               id="register_input_repassword"
                                               style="width: 100%;" />
                                    </div>          
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="register-error-placeholder repassword"></div>
                            </td>
                        </tr>
                    </table>
                </div>
                <div style="text-align: center; margin-bottom: 4px; margin-top: 16px;">
                    By clicking Register, you agree to our <a href="/index/terms/" target="_blank">Terms</a>
                </div>
                <div class="error" id="register_error" style="float: left; max-width: 202px; margin-top: 19px;">
                </div>
                <div style="width: 98px; height: 44px; float: right; margin-top: 10px;">
                    <button 
                        tabindex="0" 
                        type="button" 
                        class="filebrowserbutton" 
                        onclick="submitRegistration();"
                        style="height: 44px;">Register
                    </button>
                </div>
            </form>
        </div>
        
        <!-- Begin Success message -->
        <div class="dialog_success" id="register_success">
            <table>
                <tr>
                    <td>
                        <img src="/img/Success1.png" width="80px" />
                    </td>
                    <td>
                        <p style="margin-left: 8px;">
                            An account activation email was sent to <span id="register_email_feedback">abc@gmail.com</span> Please follow the link in the email to complete registration.
                        </p>
                    </td>
                </tr>
            </table>
        </div>
        <!-- End success message -->
        
        <script type="text/javascript">
            loadLogin();
            loadRegistration();
        </script>
        <!-- end of register -->
    </div> 
</div>