<div id="loginregister" class="loginregister">
    <div class="loginregister_header">
        <a class="loginregister_tab active">
            <span class="dialogfont " style="left: 79px;">Sign In</span>
        </a>
        <a class="loginregister_tab">
            <span class="dialogfont" style="left: 74px;">Register</span>
        </a>
    </div>
    <div class="loginregister_body dialogbg">
        <div style="width: 330px; margin-right: auto; margin-bottom: 0px; margin-left: auto; height: 242px; position: relative; top: 67px;" id="login">
            <div style="height: 57px;">
                <table style="width: 100%;">
                    <tr>
                        <td>
                            Email
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="front-card">
                                <div class="placeholding-input searchcourse flex-table-form">
                                     <input 
                                        type="text" 
                                        autocomplete="on" 
                                        title="Email" 
                                        name="email" 
                                        class="text-input email-input"
                                        style="width: 100%"
                                        maxlength="100" />
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <div style="height: 57px; margin-top: 10px;">
                <table style="width: 100%; height: 100%;">
                    <tr>
                        <td>
                            Password
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="front-card">
                                <div class="placeholding-input searchcourse flex-table-form">
                                    <input 
                                        type="password" 
                                        title="Password" 
                                        name="password"
                                        style="width: 100%;"
                                        class="text-input email-input"
                                        maxlength="100" />
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a href="/login/forgot" class="forgot2">Forgot your password?</a>
                        </td>
                    </tr>
                </table>
            </div>
            <div style="">
                <div style="">
                    <label class="remember">
                        <input type="checkbox" name="rememberme" value="1" checked="on"/>
                        <span>Remember me</span>
                    </label>
                </div>
                <div style="">
                    <button 
                            class="filebrowserbutton" 
                            type="submit" 
                            tabindex="0">Login
                    </button>
                </div>
            </div>
        </div>
    </div> 
</div>