<?php
/**
 * the email template for registration
 * $this -> sLink the link for the user to activate his account
 */
?>
<html>
    <body>
        <table style="width: 100%;">
            <tr>
                <td></td>
                <!-- the main body  -->
                <td style="background-color: rgb(232, 232, 232);width: 700px;">
                    <table style="width: 100%;">
                        <tr style="height: 12px;">
                            <td></td><td></td><td></td>
                        </tr>
                        <tr>
                            <td style="width: 12px;"></td>
                            <!-- begin main dialog -->
                            <td style="background-color: white; border-radius: 30px 30px 30px 30px; box-shadow: 0px 10px 5px rgb(136, 136, 136);">
                                <table style="width: 100%;">
                                    <tr style="height: 30px;">
                                        <td style="width: 90px;"></td><td></td><td style="width: 90px;"></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>
                                            <p style="text-align: center">
                                                Please confirm your Nerdeez account registration by clicking 
                                                <a href="<?php echo $this -> sLink; ?>" style="color: #E62A59; text-decoration: underline;">THIS LINK</a>
                                            </p>
                                            <p style="text-align: center">
                                                Regards, Nerdeez team.
                                            </p>
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr style="height: 30px;">
                                        <td></td><td></td><td></td>
                                    </tr>
                                </table>
                            </td>
                            <!-- end main dialog -->
                            <td style="width: 12px;"></td>
                        </tr>
                        <tr style="height: 12px;">
                            <td></td><td></td><td></td>
                        </tr>
                    </table>
                </td>
                <!-- end of main body -->
                <td></td>
            </tr>
        </table>
    </body>
</html>