<?php
/**
 * attaching this partial will add upload capabilities
 * @param String $this -> sId the id of the form
 * @param int $this -> iSerial the serial identifier for the files uploaded
 * @param int $this -> iNumUpload number of uploads allowed
 * @param int $this -> iMaxSize the max file size
 * @param String $this -> sAcceptFileTypes regular string of the file types allowed
 * @param String $this -> sUrl thee url to upload to
 */
?>


 <div id="<?php echo $this -> sId; ?>">
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
        <div class="span7">
            <div class="fileupload-buttonbar" style="height:20px">
                <label class="fileinput-button">
                    <span>Upload</span>
                </label>
                <div class="hidder"></div>
                <div style="position: relative; left: -94px; opacity: 0; top: -64px;">
                    <input type="file" 
                           style="height: 30px; cursor: pointer;" 
                           multiple="multiple" 
                           name="files[]"
                           data-url="/filemanager/upload/"
                           />
                </div>
            </div>
        </div>
    </div>
    
    <div class="dropzone">
        <h1>
            Drop files here
        </h1>
    </div>
    
    <!-- The loading indicator is shown during file processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery">
            <tr class="filesheader">
                <td class="filebrowser-td">Filename</td>
                <td class="filebrowser-td filebrowser-td-left">Size</td>
                <td class="filebrowser-td filebrowser-td-left">Progress</td>
                <td class="filebrowser-td filebrowser-td-left">Delete</td>
            </tr>
    </tbody></table>
<!--</form>-->
</div>


<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="1"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td style="padding-left: 5px; padding-right: 5px;width:50%;">
                <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>
            </td>
            
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <img src="/img/trash.png" />
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="1"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            
            <td class="name">
                {%=file.name%}
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td  style="color: green; font-weight: bold; width: 100%;border-right: 1px solid #DDDDDD;">COMPLETE</td>
        {% } %}
        <td class="delete">
            <button class="btn btn-warning" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <img src="/img/trash.png" />
            </button>
        </td>
    </tr>
{% } %}
</script>



<script type="text/javascript">
ksInitUpload('<?php echo $this -> sId; ?>' , <?php echo $this -> iSerial; ?> , <?php echo $this -> iNumUpload; ?> , <?php echo $this -> iMaxSize; ?>, <?php echo $this -> sAcceptFileTypes; ?> , '<?php echo $this -> sUrl; ?>' );
</script>