<?php
/**
 * edit the countries table
 * @param Zend_Db_Table_Rowset $this -> rsUniversities the uni we have
 * @param Zend_Db_Table_Rowset $this -> rsCourses all the countries
 * @param String $this -> sError
 * @param String $this -> sStatus 
 */
?>

<?php
//include the admin script
$this->headScript()->appendFile('/js/admin.js');
?>

<div class="inview-wrapper">
    
    <?php 
    //create the status divs
    ?>
    <div id="error" class="about_status"><?php echo $this -> sError; ?></div>
    <div id="status" class="about_status"><?php echo $this -> sStatus; ?></div>

    <table style="width: 100%;">
        <tr>
            <td>

            </td>
            <td>
                ID
            </td>
            <td>
                Title
            </td>
            <td>
                Description
            </td>
            <td>
                University
            </td>
            <td>
                Website
            </td>
            <td>
                Connections
            </td>
            <td>
                Delete
            </td>
            <td>
                Update
            </td>
            <td>
                Details
            </td>
        </tr>
        <?php
        foreach ($this -> rsCourses as $rCourse) {
        ?>

        <tr id="course_<?php echo $rCourse['id']; ?>"> 
            <td>
                <input class="ksFileBrowserCheckbox" type="checkbox" val="<?php echo $rCourse['id']; ?>" />
            </td>
            <td>
                <?php echo $rCourse['id']; ?>
            </td>
            <td>
                <p class="title" contenteditable="true">
                        <?php echo $rCourse['title']; ?>
                </p>
            </td>
            <td>
                <p class="description" contenteditable="true">
                    <?php echo $rCourse['description']; ?>
                </p>
            </td>
            <td>
                <select name="university">
                    <?php
                        foreach (clone $this -> rsUniversities as $rUniversity){
                            if ($rCourse['universities_id'] == $rUniversity['id']){
                    ?>
                    
                    <option selected="selected" value="<?php echo $rUniversity['id']; ?>"><?php echo $rUniversity['title']; ?></option>
                    
                    <?php
                            }
                            else{
                    ?>
                    
                    <option value="<?php echo $rUniversity['id']; ?>"><?php echo $rUniversity['title']; ?></option>
                    
                    <?php
                            }
                        }
                    ?>
                </select>
            </td>
            
            <td>
                <p class="website" contenteditable="true">
                    <?php echo $rCourse['website']; ?>
                </p>
            </td>
            <td>
                <p class="connections" contenteditable="true">
                    <?php echo $rCourse['connections']; ?>
                </p>
            </td>
            <td>
                <a href="javascript:void(0)" onclick="ksDeleteCourse(<?php echo $rCourse['id']; ?>)">
                    <img src="/img/deletebutton.png" />
                </a>
            </td>
            <td>
                <a href="javascript:void(0)" onclick="ksUpdateCourse(<?php echo $rCourse['id']; ?>)">
                    <img src="/img/32_save.png" />
                </a>
            </td>
            <td>
                <a href="/admin/course/id/<?php echo $rCourse['id']; ?>">Details</a>
            </td>
        </tr>

        <?php
        }
        ?>
    </table>
    <br/>
    <a href="javascript:void(0)" onclick="ksDeleteSelectedCourses()">
    Delete selected Courses
    </a>
    <br/>
    <br/>
    <br/> 
    <h2>Add new Course</h2>
    <form action="/admin/addcourse" method="post">
        <table>
            <tr>
                <td>
                    Title:
                </td>
                <td>
                    <input type="text" name="title" />
                </td>
            </tr>
            <tr>
                <td>
                    Description:
                </td>
                <td>
                    <input type="text" name="description" />
                </td>
            </tr>
            <tr>
                <td>
                    Connections:
                </td>
                <td>
                    <input type="text" name="connections" />
                </td>
            </tr>
            <tr>
                <td>
                    University:
                </td>
                <td>
                    <select name="university">
                        <?php
                        foreach (clone $this -> rsUniversities as $rUniversity){
                        ?>
                        <option value="<?php echo $rUniversity['id']; ?>"><?php echo $rUniversity['title']; ?></option>
                        <?php
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Website:
                </td>
                <td>
                    <input type="text" name="website" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <button value="Submit" type="submit" style="width: 100px; height: 30px">Submit
                    </button>
                </td>
            </tr>
        </table>
    </form>
    
    <?php
    //create the serial number
    $serial = rand(0, 99999);
    ?>
    
    <br/>
    <br/>
    <br/>
    <h2>add rows to table via csv file:</h2>
    <form method="post" action="/admin/insertbycvs">
        
        <?php 
            //the upload type
            echo $this -> partial('partials/uploadbutton.phtml' , array('iSerial' => $serial , 'sId' => 'uploadFileBrowser' , 'iNumUpload' => 1 , 'iMaxSize' => 209715200 , 'sAcceptFileTypes' => '/(\\.|\\/)(csv)$/i')) ;
        ?>
        
        <input type="hidden" name="serial" value="<?php echo $serial; ?>" />
        <input type="hidden" name="model" value="Application_Model_DbTable_Courses" />
        <button type="submit" style="width: 100px; height: 30px">Submit</button>
    </form>


</div>