<?php
/**
 * this file will add specific admin operations for the files 
 */
?>

<input type="file" multiple="multiple" name="files[]" id="adminzipupload_input" class="adminupload_input"/>

<!-- start of zip file add form -->
<div class="admin_container">
    <h2>Add files by zip</h2>
    <p style="text-align: center;">
        The hirechy is from university -&gt; course -&gt; papaFolder -&gt; sonFolder | file -&gt; file
    </p>
    <div class="addbyzip" style="width: 500px; margin: 0 auto;">
        <form method="post" action="/admin/addbyzip/">
            <table>
                <tr>
                    <td colspan="2">
                        <?php
                            $serial = rand(0, 99999);
                            //echo $this -> partial('partials/uploadbutton.phtml' , array('iSerial' => $serial , 'sId' => 'uploadZipFiles' , 'iNumUpload' => 1 , 'iMaxSize' => 209715200 , 'sAcceptFileTypes' => '/(\\.|\\/)(zip)$/i' , 'sUrl' => '/admin/upload')) ;
                        ?>
                        <div id="adminzipupload" class="adminupload" onclick="$('#adminzipupload_input').click();">
                            <span>upload</span>
                        </div>
                        <div id="adminzipupload_files">
                            <table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery">
                                <tr class="filesheader">
                                    <td class="filebrowser-td">Filename</td>
                                    <td class="filebrowser-td filebrowser-td-left">Size</td>
                                    <td class="filebrowser-td filebrowser-td-left">Progress</td>
                                    <td class="filebrowser-td filebrowser-td-left">Delete</td>
                                </tr>
                            </tbody></table> 
                        </div>
                        <script type="text/javascript">
                            ksInitUpload('adminzipupload' , 
                                <?php echo $serial; ?> , 
                                    1 , 
                                    0, 
                                    '/(\\.|\\/)(zip)$/i' , 
                                    '/admin/upload/');
                        </script>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: center">
                        <input type="hidden" name="serial" value="<?php echo $serial; ?>">
                        <button tabindex="0" type="submit" class="submit btn primary-btn js-submit">
                            Submit
                        </button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>
<!-- end of zip add files dialog -->

<!-- start of s3 clean dialog --> 
<div class="admin_container">
    <h2>Clean my s3</h2>
    <div style="width: 500px; margin: 0 auto;">
        <form method="post" action="/admin/cleans3/" style="text-align: center">
            <button tabindex="0" type="submit" class="submit btn primary-btn js-submit">
                Submit
            </button>
        </form>
    </div>
</div>
<!-- end of s3 clean dialog --> 