<?php
/**
 * where the admin add stuff to the database
 */
?>

<?php
//include the js and css for the tabs
//$this->headScript()->appendFile('/js/admin.js');
?>

<div class="inview-wrapper">
    
    <!--<a href="/admin/countries/">
        Countries
    </a>
    <br/>-->
    
    <a href="/admin/universities/">
        Universities
    </a>
    <br/>
    
    <a href="/admin/courses/">
        Courses
    </a>
    <br/>
    
    <a href="/admin/folders/">
        Folders
    </a>
    <br/>
    <a href="/admin/files/">
        Files
    </a>
    <br/>
    <a href="/admin/database/">
        database
    </a>
    <br/>
    
    <!--
    
    <a href="/admin/semesters/">
        Semesters 
    </a>
    <br/>
    
    <a href="/admin/pngs/">
        Pngs 
    </a>
    <br/>
    <a href="/admin/rules/">
        Rules 
    </a>
    <br/>-->
    
</div>