<?php
/**
 * edit the countries table
 * @param Zend_Db_Table_Rowset $this -> rsUniversities the uni we have
 * @param Zend_Db_Table_Abstract $this -> mUniversities the table model
 * @param String $this -> sError
 * @param String $this -> sStatus 
 */
?>

<?php
//include the admin script
$this->headScript()->appendFile('/js/admin.js');
?>

<div class="inview-wrapper">
    
    <?php 
    //create the status divs
    ?>
    <div id="error" class="about_status"><?php echo $this -> sError; ?></div>
    <div id="status" class="about_status"><?php echo $this -> sStatus; ?></div>

    <?php
    echo $this -> partial ('partials/adminInsertUpdateDelete.phtml' , array('rsRows' => $this -> rsUnicersities , 'mModel' => $this -> mUniversities));
    ?>
    
    <table style="width: 100%;">
        <tr>
            <td>

            </td>
            <td>
                Title
            </td>
            <td>
                Description
            </td>
            <td>
                Image
            </td>
            <td>
                Country
            </td>
            <td>
                WebSite
            </td>
            <td>
                Delete
            </td>
            <td>
                Update
            </td>
        </tr>
        <?php
        foreach ($this -> rsUniversities as $rUniversity) {
        ?>

        <tr id="university_<?php echo $rUniversity['id']; ?>"> 
            <td>
                <input class="ksFileBrowserCheckbox" type="checkbox" val="<?php echo $rUniversity['id']; ?>" />
            </td>
            <td>
                <p class="title" contenteditable="true">
                    <?php echo $rUniversity['title']; ?>
                </p>
            </td>
            <td>
                <p class="description" contenteditable="true">
                    <?php echo $rUniversity['description']; ?>
                </p>
            </td>
            <td>
                <p class="image" contenteditable="true">
                    <?php echo $rUniversity['image']; ?>
                </p>
            </td>
            <td>
                <select name="country">
                    <?php
                        foreach (clone $this -> rsCountries as $rCountry){
                            if ($rUniversity['countries_id'] == $rCountry['id']){
                    ?>
                    
                    <option selected="selected" value="<?php echo $rCountry['id']; ?>"><?php echo $rCountry['title']; ?></option>
                    
                    <?php
                            }
                            else{
                    ?>
                    
                    <option value="<?php echo $rCountry['id']; ?>"><?php echo $rCountry['title']; ?></option>
                    
                    <?php
                            }
                        }
                    ?>
                </select>
            </td>
            <td>
                <p class="website" contenteditable="true">
                    <?php echo $rUniversity['website']; ?>
                </p>
            </td>
            <td>
                <a href="javascript:void(0)" onclick="ksDeleteUniversity(<?php echo $rUniversity['id']; ?>)">
                    <img src="/img/deletebutton.png" />
                </a>
            </td>
            <td>
                <a href="javascript:void(0)" onclick="ksUpdateUniversity(<?php echo $rUniversity['id']; ?>)">
                    <img src="/img/32_save.png" />
                </a>
            </td>
        </tr>

        <?php
        }
        ?>
    </table>
    <br/>
    <a href="javascript:void(0)" onclick="ksDeleteSelectedUniversities()">
    Delete selected countries
    </a>
    <br/>
    <br/>
    <br/> 
    <h2>Add new country</h2>
    <form action="/admin/adduniversity" method="post">
        <table>
            <tr>
                <td>
                    Title:
                </td>
                <td>
                    <input type="text" name="title" />
                </td>
            </tr>
            <tr>
                <td>
                    Description:
                </td>
                <td>
                    <input type="text" name="description" />
                </td>
            </tr>
            <tr>
                <td>
                    Image url:
                </td>
                <td>
                    <input type="text" name="image" />
                </td>
            </tr>
            <tr>
                <td>
                    Country:
                </td>
                <td>
                    <select name="country">
                        <?php
                        foreach (clone $this -> rsCountries as $rCountry){
                        ?>
                        <option value="<?php echo $rCountry['id']; ?>"><?php echo $rCountry['title']; ?></option>
                        <?php
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    Website:
                </td>
                <td>
                    <input type="text" name="website" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <button value="Submit" type="submit" style="width: 100px; height: 30px">Submit
                    </button>
                </td>
            </tr>
        </table>
    </form>


</div>